name: Test SSH Secret

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH key format
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "Length: ${#SSH_KEY}"

          if [[ "$SSH_KEY" == "-----BEGIN OPENSSH PRIVATE KEY-----"* ]]; then
            echo "Correct beginning"
          else
            echo "Wrong beginning"
          fi

          if [[ "$SSH_KEY" == *"-----END OPENSSH PRIVATE KEY-----" ]]; then
            echo "Correct ending"
          else
            echo "Wrong ending"
          fi